version: 2.1
jobs:
   scan:
      docker:
          - image: circleci/python:latest
      working_directory: ~/repo
      steps:
          - checkout
          - run: sudo pip install trufflehog
          - run: trufflehog --help
          - run: trufflehog --json --regex ~/repo

workflows:
  scan_image:
    jobs:
      - scan
