version: 2.1
jobs:
   scan:
      docker:
          - image: circleci/python:latest
      working_directory: ~/repo
      steps:
          - checkout
          - run: sudo pip install trufflehog
          - run: ls ~/repo
          - run: trufflehog  --rules ~/repo/rules --max_depth 1 ~/repo

workflows:
  scan_image:
    jobs:
      - scan
